SUBROUTINE DEMO.CCY.VALID

$INSERT I_COMMON
$INSERT I_EQUATE
$INSERT I_F.CURRENCY


    CCY.NAME = R.NEW(EB.CUR.CCY.NAME)<1,1>
    
    IF CCY.NAME EQ 'TESTCCYJCB' THEN
        ETEXT = 'STB demo CI/CD: No TESTCCYJCB value allowed'
        CALL STORE.END.ERROR
    END

    RETURN
END
